//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL.dbconnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.History_reader_ticket = new HashSet<History_reader_ticket>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> ID_author { get; set; }
        public Nullable<System.DateTime> YearMade { get; set; }
        public Nullable<int> ID_creat_build { get; set; }
        public Nullable<int> ID_Janr { get; set; }
        public Nullable<int> CountPage { get; set; }
    
        public virtual Autor Autor { get; set; }
        public virtual Creat_Build Creat_Build { get; set; }
        public virtual Janr Janr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<History_reader_ticket> History_reader_ticket { get; set; }
    }
}
