//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL.dbconnection
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LibEntities : DbContext
    {
        public LibEntities()
            : base("name=LibEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Autor> Autor { get; set; }
        public virtual DbSet<Book> Book { get; set; }
        public virtual DbSet<Creat_Build> Creat_Build { get; set; }
        public virtual DbSet<Employee1> Employee1 { get; set; }
        public virtual DbSet<History_reader_ticket> History_reader_ticket { get; set; }
        public virtual DbSet<Janr> Janr { get; set; }
        public virtual DbSet<Post> Post { get; set; }
        public virtual DbSet<Reader> Reader { get; set; }
        public virtual DbSet<Reader_Ticket> Reader_Ticket { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
