//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL.dbconnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reader_Ticket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reader_Ticket()
        {
            this.History_reader_ticket = new HashSet<History_reader_ticket>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ID_Emp { get; set; }
        public Nullable<int> ID_Reader { get; set; }
        public Nullable<System.DateTime> DateReg { get; set; }
    
        public virtual Employee1 Employee1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<History_reader_ticket> History_reader_ticket { get; set; }
        public virtual Reader Reader { get; set; }
    }
}
